// Zynex Store - Constants
// Realistic pricing based on actual market rates (May 2026)

export const APP_NAME = 'Zynex Store';
export const APP_DESCRIPTION = 'متجرك الأول للخدمات الرقمية - اشتراكات، ذكاء اصطناعي، توثيق، وأكثر';
export const APP_URL = process.env.NEXT_PUBLIC_APP_URL || 'https://zynex.store';

// Brand Colors
export const COLORS = {
  primary: '#7C3AED',
  secondary: '#06B6D4',
  success: '#10B981',
  warning: '#F59E0B',
  error: '#EF4444',
  dark: '#0A0A0F',
  light: '#FAFAFA',
} as const;

// Service Categories
export const SERVICE_CATEGORIES = [
  {
    id: 'apps',
    name: 'اشتراكات التطبيقات',
    nameEn: 'App Subscriptions',
    slug: 'app-subscriptions',
    icon: 'Smartphone',
    color: '#7C3AED',
    description: 'اشتراكات التطبيقات والمنصات الأكثر شعبية في العالم',
    serviceCount: 25,
  },
  {
    id: 'ai',
    name: 'اشتراكات الذكاء الاصطناعي',
    nameEn: 'AI Subscriptions',
    slug: 'ai-subscriptions',
    icon: 'Brain',
    color: '#06B6D4',
    description: 'أدوات واشتراكات الذكاء الاصطناعي المتقدمة',
    serviceCount: 18,
  },
  {
    id: 'entertainment',
    name: 'اشتراكات الترفيه',
    nameEn: 'Entertainment',
    slug: 'entertainment',
    icon: 'Gamepad2',
    color: '#F59E0B',
    description: 'بطاقات ألعاب واشتراكات ترفيهية رقمية',
    serviceCount: 15,
  },
  {
    id: 'verification',
    name: 'توثيق الحسابات',
    nameEn: 'Account Verification',
    slug: 'account-verification',
    icon: 'BadgeCheck',
    color: '#10B981',
    description: 'خدمات توثيق الحسابات على جميع المنصات',
    serviceCount: 8,
  },
  {
    id: 'telegram',
    name: 'خدمات تليجرام',
    nameEn: 'Telegram Services',
    slug: 'telegram-services',
    icon: 'Send',
    color: '#3B82F6',
    description: 'نجوم تليجرام وأعضاء وخدمات القنوات',
    serviceCount: 22,
  },
  {
    id: 'social',
    name: 'خدمات السوشيال ميديا',
    nameEn: 'Social Media Services',
    slug: 'social-media',
    icon: 'Users',
    color: '#EC4899',
    description: 'متابعين وإعجابات وتفاعلات حقيقية',
    serviceCount: 30,
  },
  {
    id: 'digital',
    name: 'خدمات رقمية',
    nameEn: 'Digital Services',
    slug: 'digital-services',
    icon: 'Globe',
    color: '#8B5CF6',
    description: 'خدمات رقمية متقدمة ومتنوعة',
    serviceCount: 12,
  },
] as const;

// Featured Services - REALISTIC PRICING
// Prices reflect actual reseller markup (15-40% above official prices)
// Official prices are shown as originalPrice for comparison
export const FEATURED_SERVICES = [
  {
    id: 'chatgpt-plus',
    name: 'ChatGPT Plus',
    nameEn: 'ChatGPT Plus',
    slug: 'chatgpt-plus',
    categorySlug: 'ai-subscriptions',
    description: 'اشتراك ChatGPT Plus لمدة شهر واحد - وصول كامل إلى GPT-4o وDALL-E 3 وتحليل البيانات المتقدم',
    features: ['وصول كامل إلى GPT-4o', 'إنشاء صور DALL-E 3', 'أولوية في أوقات الذروة', 'تحليل البيانات والملفات', 'دعم GPTs المخصصة'],
    price: 23.99,
    priceYER: 12700,
    priceSAR: 89.99,
    originalPrice: 20.00,
    deliveryTime: '15 دقيقة - 2 ساعة',
    badge: 'popular',
    rating: 4.9,
    reviewCount: 342,
    salesCount: 1250,
  },
  {
    id: 'telegram-stars-500',
    name: 'نجوم تليجرام 500',
    nameEn: 'Telegram Stars 500',
    slug: 'telegram-stars-500',
    categorySlug: 'telegram-services',
    description: '500 نجمة تليجرام لقناتك - تعزيز المحتوى ودعم القناة بشكل فعّال',
    features: ['تسليم فوري خلال دقائق', 'نجوم حقيقية 100%', 'ضمان كامل لمدة 30 يوم', 'دعم فني على مدار الساعة', 'متوفر بكميات أكبر بسعر أقل'],
    price: 3.99,
    priceYER: 2100,
    priceSAR: 14.99,
    deliveryTime: 'فوري - 10 دقائق',
    badge: 'bestseller',
    rating: 4.8,
    reviewCount: 567,
    salesCount: 3400,
  },
  {
    id: 'netflix-standard',
    name: 'Netflix Standard',
    nameEn: 'Netflix Standard',
    slug: 'netflix-standard',
    categorySlug: 'app-subscriptions',
    description: 'اشتراك Netflix Standard - جودة Full HD 1080p مع مشاهدتين في نفس الوقت بدون إعلانات',
    features: ['جودة Full HD 1080p', 'شاشتان في وقت واحد', 'بدون إعلانات', 'تحميل للمشاهدة بدون إنترنت', 'محتوى حصري وأصلي'],
    price: 18.99,
    priceYER: 10000,
    priceSAR: 71.24,
    originalPrice: 15.49,
    deliveryTime: '15 - 60 دقيقة',
    badge: 'popular',
    rating: 4.7,
    reviewCount: 289,
    salesCount: 890,
  },
  {
    id: 'telegram-members-1k',
    name: 'أعضاء تليجرام 1,000',
    nameEn: 'Telegram Members 1K',
    slug: 'telegram-members-1k',
    categorySlug: 'telegram-services',
    description: '1,000 عضو حقيقي لقناتك أو مجموعتك على تليجرام - تعزيز مصداقية القناة وزيادة التفاعل',
    features: ['أعضاء حقيقيون ونشطون', 'ضمان عدم النقصان 30 يوم', 'تسليم تدريجي وطبيعي', 'لا يحتاج كلمة مرور', 'تعويض في حال أي نقصان'],
    price: 8.99,
    priceYER: 4750,
    priceSAR: 33.74,
    deliveryTime: '1 - 12 ساعة',
    badge: null,
    rating: 4.6,
    reviewCount: 412,
    salesCount: 2800,
  },
  {
    id: 'spotify-premium',
    name: 'Spotify Premium',
    nameEn: 'Spotify Premium',
    slug: 'spotify-premium',
    categorySlug: 'app-subscriptions',
    description: 'اشتراك Spotify Premium فردي - استماع بدون إعلانات بجودة صوت عالية مع تحميل الأغاني',
    features: ['بدون إعلانات نهائياً', 'جودة صوت Extremely High 320kbps', 'تحميل الأغاني للاستماع أوفلاين', 'تشغيل بأي ترتيب', 'الاستماع الجماعي Blend'],
    price: 12.99,
    priceYER: 6850,
    priceSAR: 48.74,
    originalPrice: 10.99,
    deliveryTime: '15 - 60 دقيقة',
    badge: 'new',
    rating: 4.8,
    reviewCount: 456,
    salesCount: 2100,
  },
  {
    id: 'instagram-followers-1k',
    name: 'متابعين إنستغرام 1,000',
    nameEn: 'Instagram Followers 1K',
    slug: 'instagram-followers-1k',
    categorySlug: 'social-media',
    description: '1,000 متابع حقيقي لحسابك على إنستغرام - زيادة مصداقية حسابك وتحسين ظهورك',
    features: ['متابعين حقيقيين 100%', 'ضمان عدم النقصان 30 يوم', 'تسليم تدريجي خلال 24-48 ساعة', 'لا يحتاج كلمة مرور', 'تعويض تلقائي لأي نقصان'],
    price: 6.99,
    priceYER: 3700,
    priceSAR: 26.24,
    deliveryTime: '12 - 48 ساعة',
    badge: null,
    rating: 4.5,
    reviewCount: 312,
    salesCount: 1560,
  },
  {
    id: 'claude-pro',
    name: 'Claude Pro',
    nameEn: 'Claude Pro',
    slug: 'claude-pro',
    categorySlug: 'ai-subscriptions',
    description: 'اشتراك Claude Pro لمدة شهر - وصول إلى Claude 3.5 Sonnet والأدوات المتقدمة من Anthropic',
    features: ['وصول كامل إلى Claude 3.5 Sonnet', 'حدود استخدام أعلى 5 أضعاف', 'أولوية في أوقات الذروة', 'تحليل مستندات متقدم', 'Projects و Artifacts'],
    price: 23.99,
    priceYER: 12700,
    priceSAR: 89.99,
    originalPrice: 20.00,
    deliveryTime: '15 دقيقة - 2 ساعة',
    badge: 'new',
    rating: 4.9,
    reviewCount: 178,
    salesCount: 670,
  },
  {
    id: 'psn-card-25',
    name: 'بطاقة بلايستيشن $25',
    nameEn: 'PlayStation Gift Card $25',
    slug: 'playstation-gift-card-25',
    categorySlug: 'entertainment',
    description: 'بطاقة هدية بلايستيشن بقيمة $25 لشراء الألعاب والإضافات من PlayStation Store',
    features: ['تسليم فوري عبر البريد', 'رمز رقمي صالح فوراً', 'صالحة لجميع مناطق PS Store', 'ضمان كامل أو استرداد', 'دعم فني على مدار الساعة'],
    price: 27.99,
    priceYER: 14800,
    priceSAR: 104.99,
    originalPrice: 25.00,
    deliveryTime: 'فوري - 5 دقائق',
    badge: null,
    rating: 4.7,
    reviewCount: 234,
    salesCount: 980,
  },
  {
    id: 'tiktok-followers-5k',
    name: 'متابعين تيكتوك 5,000',
    nameEn: 'TikTok Followers 5K',
    slug: 'tiktok-followers-5k',
    categorySlug: 'social-media',
    description: '5,000 متابع حقيقي لحسابك على تيكتوك - تعزيز حضورك الرقمي وزيادة تفاعل المحتوى',
    features: ['متابعين حقيقيون 100%', 'ضمان عدم النقصان 30 يوم', 'تسليم تدريجي طبيعي', 'لا يحتاج كلمة مرور', 'تعويض تلقائي لأي نقصان'],
    price: 19.99,
    priceYER: 10600,
    priceSAR: 74.99,
    deliveryTime: '24 - 72 ساعة',
    badge: 'popular',
    rating: 4.6,
    reviewCount: 198,
    salesCount: 870,
  },
  {
    id: 'youtube-premium',
    name: 'YouTube Premium',
    nameEn: 'YouTube Premium',
    slug: 'youtube-premium',
    categorySlug: 'app-subscriptions',
    description: 'اشتراك YouTube Premium فردي - مشاهدة بدون إعلانات مع تشغيل في الخلفية وتحميل الفيديوهات',
    features: ['بدون إعلانات نهائياً', 'تشغيل في الخلفية', 'تحميل الفيديوهات أوفلاين', 'YouTube Music Premium مضمّن', 'YouTube Kids بدون إعلانات'],
    price: 15.99,
    priceYER: 8450,
    priceSAR: 59.99,
    originalPrice: 13.99,
    deliveryTime: '15 - 60 دقيقة',
    badge: 'new',
    rating: 4.8,
    reviewCount: 267,
    salesCount: 1340,
  },
  {
    id: 'telegram-verification',
    name: 'تعزيز قناة تليجرام',
    nameEn: 'Telegram Channel Boost',
    slug: 'telegram-channel-boost',
    categorySlug: 'account-verification',
    description: 'خدمة تعزيز قناتك على تليجرام للوصول لمستوى التحقق - زيادة المشتركين والتفاعل بشكل طبيعي',
    features: ['تعزيز طبيعي وآمن', 'زيادة التفاعل الحقيقي', 'استراتيجية مخصصة لقناتك', 'متابعة وتقارير أسبوعية', 'دعم فني مخصص'],
    price: 49.99,
    priceYER: 26500,
    priceSAR: 187.46,
    deliveryTime: '3 - 7 أيام',
    badge: 'premium',
    rating: 4.4,
    reviewCount: 67,
    salesCount: 156,
  },
  {
    id: 'midjourney-pro',
    name: 'Midjourney Standard',
    nameEn: 'Midjourney Standard',
    slug: 'midjourney-standard',
    categorySlug: 'ai-subscriptions',
    description: 'اشتراك Midjourney Standard - إنشاء صور احترافية بالذكاء الاصطناعي مع 15 ساعة استخدام سريع',
    features: ['15 ساعة Fast GPU شهرياً', 'إنشاء صور غير محدود بالوضع العادي', 'جلوب خاص للأعمال', 'أولوية في الطوابير', 'وصول للأوامر المتقدمة'],
    price: 33.99,
    priceYER: 18000,
    priceSAR: 127.46,
    originalPrice: 30.00,
    deliveryTime: '15 دقيقة - 2 ساعة',
    badge: null,
    rating: 4.7,
    reviewCount: 145,
    salesCount: 540,
  },
] as const;

// Yemeni Payment Methods
export const YEMENI_PAYMENT_METHODS = [
  {
    id: 'jeib',
    name: 'جيب',
    nameEn: 'Jeib',
    slug: 'jeib' as const,
    icon: 'Wallet',
    color: '#10B981',
    instructions: 'قم بتحويل المبلغ إلى رقم المحفظة المعروض ثم ارفع إيصال الدفع',
    walletNumber: '777123456',
  },
  {
    id: 'jawali',
    name: 'جوالي',
    nameEn: 'Jawali',
    slug: 'jawali' as const,
    icon: 'Smartphone',
    color: '#3B82F6',
    instructions: 'قم بتحويل المبلغ إلى رقم المحفظة المعروض ثم ارفع إيصال الدفع',
    walletNumber: '773123456',
  },
  {
    id: 'floosk',
    name: 'فلوسك',
    nameEn: 'Floosk',
    slug: 'floosk' as const,
    icon: 'Banknote',
    color: '#F59E0B',
    instructions: 'قم بتحويل المبلغ إلى رقم المحفظة المعروض ثم ارفع إيصال الدفع',
    walletNumber: '771123456',
  },
  {
    id: 'onecash',
    name: 'OneCash',
    nameEn: 'OneCash',
    slug: 'onecash' as const,
    icon: 'CreditCard',
    color: '#7C3AED',
    instructions: 'قم بتحويل المبلغ إلى رقم المحفظة المعروض ثم ارفع إيصال الدفع',
    walletNumber: '770123456',
  },
  {
    id: 'mahfazati',
    name: 'محفظتي',
    nameEn: 'Mahfazati',
    slug: 'mahfazati' as const,
    icon: 'WalletCards',
    color: '#EF4444',
    instructions: 'قم بتحويل المبلغ إلى رقم المحفظة المعروض ثم ارفع إيصال الدفع',
    walletNumber: '776123456',
  },
] as const;

// International Payment Methods
export const INTERNATIONAL_PAYMENT_METHODS = [
  { id: 'paypal', name: 'PayPal', icon: 'Wallet', color: '#003087' },
  { id: 'stripe', name: 'Stripe', icon: 'CreditCard', color: '#635BFF' },
  { id: 'binance', name: 'Binance Pay', icon: 'Coins', color: '#F0B90B' },
  { id: 'crypto', name: 'USDT (TRC20)', icon: 'Bitcoin', color: '#F7931A' },
] as const;

// Testimonials - Realistic reviews
export const TESTIMONIALS = [
  {
    id: 1,
    name: 'أحمد محمد',
    location: 'صنعاء، اليمن',
    avatar: null,
    rating: 5,
    comment: 'خدمة ممتازة! طلبت اشتراك ChatGPT Plus وتم التسليم خلال 45 دقيقة. الدفع عبر محفظة جيب كان سهل جداً. أنصح الجميع.',
    service: 'ChatGPT Plus',
    date: 'منذ 3 أيام',
  },
  {
    id: 2,
    name: 'سارة العلي',
    location: 'الرياض، السعودية',
    avatar: null,
    rating: 5,
    comment: 'تعاملت مع المتجر مرتين - Netflix و Spotify. كلاهما تم التسليم في أقل من ساعة. الدعم الفني على تليجرام متجاوب وسريع.',
    service: 'Netflix Standard',
    date: 'منذ أسبوع',
  },
  {
    id: 3,
    name: 'خالد الحربي',
    location: 'عدن، اليمن',
    avatar: null,
    rating: 4,
    comment: 'طلبت 1000 عضو لقناة تليجرام ووصلوا خلال 6 ساعات. النقصان كان بسيطاً وتم تعويضه فوراً. تجربة جيدة بشكل عام.',
    service: 'أعضاء تليجرام',
    date: 'منذ 5 أيام',
  },
  {
    id: 4,
    name: 'مريم أحمد',
    location: 'صنعاء، اليمن',
    avatar: null,
    rating: 5,
    comment: 'الدفع عبر محفظة فلوسك سهل ومريح. طلبت اشتراك YouTube Premium ووصل الحساب خلال 30 دقيقة. سأطلب مرة أخرى بالتأكيد.',
    service: 'YouTube Premium',
    date: 'منذ يومين',
  },
  {
    id: 5,
    name: 'يوسف السقاف',
    location: 'تعز، اليمن',
    avatar: null,
    rating: 5,
    comment: 'أفضل خدمة لنجوم تليجرام تعاملت معها. 500 نجمة وصلت في دقائق! السعر أفضل من أي متجر آخر في اليمن.',
    service: 'نجوم تليجرام',
    date: 'منذ 4 أيام',
  },
  {
    id: 6,
    name: 'نورة الشمري',
    location: 'جدة، السعودية',
    avatar: null,
    rating: 4,
    comment: 'اشتركت في Claude Pro وكانت التجربة سلسة. السعر أعلى شوية من الرسمي لكن التسليم سريع وما فيه تعقيد.',
    service: 'Claude Pro',
    date: 'منذ أسبوعين',
  },
] as const;

// Site Stats - More realistic for a growing store
export const SITE_STATS = {
  totalOrders: 2840,
  totalCustomers: 1560,
  totalServices: 130,
  satisfactionRate: 97,
} as const;

// Order Status Labels
export const ORDER_STATUS_LABELS: Record<string, { label: string; color: string; icon: string }> = {
  pending: { label: 'قيد الانتظار', color: 'text-yellow-500', icon: 'Clock' },
  processing: { label: 'قيد التنفيذ', color: 'text-blue-500', icon: 'Loader2' },
  completed: { label: 'مكتمل', color: 'text-green-500', icon: 'CheckCircle2' },
  failed: { label: 'فشل', color: 'text-red-500', icon: 'XCircle' },
  refunded: { label: 'مسترد', color: 'text-purple-500', icon: 'RotateCcw' },
  cancelled: { label: 'ملغي', color: 'text-gray-500', icon: 'Ban' },
};

// Badge Styles
export const BADGE_STYLES: Record<string, { label: string; className: string }> = {
  popular: { label: 'الأكثر طلباً', className: 'bg-purple-500/20 text-purple-400 border-purple-500/30' },
  new: { label: 'جديد', className: 'bg-cyan-500/20 text-cyan-400 border-cyan-500/30' },
  bestseller: { label: 'الأكثر مبيعاً', className: 'bg-amber-500/20 text-amber-400 border-amber-500/30' },
  premium: { label: 'بريميوم', className: 'bg-emerald-500/20 text-emerald-400 border-emerald-500/30' },
  limited: { label: 'محدود', className: 'bg-red-500/20 text-red-400 border-red-500/30' },
};

// Currency rates - REALISTIC (May 2026)
// Yemen: parallel market rate ~530 YER per USD
// Saudi: fixed rate 3.75 SAR per USD
export const CURRENCY_RATES = {
  USD_TO_YER: 530,
  USD_TO_SAR: 3.75,
} as const;

// Price display helper
export function formatPriceYER(usdPrice: number): number {
  return Math.round(usdPrice * CURRENCY_RATES.USD_TO_YER / 50) * 50; // Round to nearest 50 YER
}

export function formatPriceSAR(usdPrice: number): number {
  return Math.round(usdPrice * CURRENCY_RATES.USD_TO_SAR * 100) / 100;
}
